services:
  frontend:
    build: ./spotifyapp/frontend
    ports:
      - "4000:4000"
    networks:
      - mynetwork
  backend:
    build: ./spotifyapp/backend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
