---
    - name: Installer et configurer le server
      hosts: all
      become: true
      tasks:

        - name: Importer le backend
          copy:
            src: "./backend"
            dest: "/root/backend"

        - name: Importer le frontend
          copy:
            src: "./frontend"
            dest: "/root/frontend"

        - name: Installer Docker
          apt:
            name: docker.io
            state: present
            update_cache: yes

        - name: Installer Docker Compose
          apt:
            name: docker-compose
            state: present
            update_cache: yes

        - name: Copier docker-compose.yml
          copy:
            src: docker-compose.yml
            dest: /root/docker-compose.yml

        - name: Lancer Docker Compose
          command: docker-compose up -d
          args:
            chdir: /root