---
    - name: Installer et configurer le server
      hosts: all
      become: true
      tasks:

        - name: Clone git
          git:
            repo: 'https://github.com/fyambos/spotifyapp.git'
            dest: /root/spotifyapp

        - name: Installer Docker
          apt:
            name: docker.io
            state: present
            update_cache: yes

        - name: Installer Docker Compose
          apt:
            name: docker-compose
            state: present
            update_cache: yes

        - name: Copier docker-compose.yml
          copy:
            src: docker-compose.yml
            dest: /root/docker-compose.yml

        - name: Lancer Docker Compose
          command: docker-compose up -d
          args:
            chdir: /root/spotifyapp